# Usa un'immagine base di Node.js
FROM node:22
# Imposta la directory di lavoro nel container
WORKDIR /channels
# Copia i file package.json e package-lock.json
COPY package*.json ./
# Installa le dipendenze
RUN npm install
# copia il resto dell'applicazione
COPY . .
# Espone la porta su cui il server Node.js sarà in ascolto
EXPOSE 5000
# Comando per avviare l'applicazione
CMD ["node", "channels.js"]